import re

DEFAULT_DATASETS_FOLDER="datasets"
DATABASE_FOLDER="database"

TOKEN_START_SENTENCE="<BOS>"
TOKEN_END_SENTENCE="<EOS>"
TOKEN_UNKNOWN_WORD="<UNK>"

WORD_REGEX = re.compile(r"\b\w+\b|[^\w\s]")